<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login - tracking</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>fe2b1611-61e9-4a8b-a5fd-f78aa1cce270</testSuiteGuid>
   <testCaseLink>
      <guid>74e255bf-3e05-4154-a0e9-314cc047ab98</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS_Renewal dan Upgrade Asuransi Aswata/Matriks 1/1.1. Login - konsumen</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>868699b6-6b99-4b02-8541-d80477b42db3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c285f53-fe93-4b9a-8601-796f610aae21</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3ab65305-e55a-4dad-914f-8204ef773477</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS_Renewal dan Upgrade Asuransi Aswata/Matriks 1/1.3. Tracking Pengajuan</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>d773233b-c914-469b-926c-d129cd6d2afd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS_Renewal dan Upgrade Asuransi Aswata/Matriks 2/2.1. Login - konsumen</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e005e89c-478a-4b68-81d6-48b0f8392190</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d61cd0e-29be-449c-8a24-26424f875a96</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9e1e57e1-89d9-4a59-9891-a3525aaf19bb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS_Renewal dan Upgrade Asuransi Aswata/Matriks 2/2.3. Tracking Pengajuan</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>33d2f3a7-2022-4399-9ea4-ff689fd0d87a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS_Renewal dan Upgrade Asuransi Aswata/Matriks 3/3.1. Login - konsumen</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae65f46c-5606-49d4-a6d3-798da4b4d155</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3aaecfa-a4a0-4ac6-8acf-62cce88b57bd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>068ba86d-8651-4a29-8a65-84e0fb3488a1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS_Renewal dan Upgrade Asuransi Aswata/Matriks 3/3.3. Tracking Pengajuan</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>49e388f7-642a-4f17-ba6f-02b9b4052981</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS_Renewal dan Upgrade Asuransi Aswata/Matriks 4/4.1. Login - konsumen</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8db92fc7-bf3d-4f32-922a-b314f0a10c99</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc9bc07e-329f-49c3-aecb-5f9644729f75</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ecc1a514-1db4-4b39-8873-3a1c5ba11e9e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS_Renewal dan Upgrade Asuransi Aswata/Matriks 4/4.3. Tracking Pengajuan</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>c449b994-a53a-40ea-90fc-e979ea609bd9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS_Renewal dan Upgrade Asuransi Aswata/Matriks 5/5.1. Login - konsumen</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>27183b61-7c49-49fe-afa8-5677a9584841</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS_Renewal dan Upgrade Asuransi Aswata/Matriks 5/5.3. Tracking Pengajuan</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>50f8563a-ceac-4dd9-9082-7fb6d445eee9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS_Renewal dan Upgrade Asuransi Aswata/Matriks 6/6.1. Login - konsumen</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3edeccc4-0ae7-43a1-885e-a5238ae64d44</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>939a6cb6-b71a-49e4-aa64-8d085c35a73a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>53bf260e-6b76-4a63-9e92-69514d683892</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS_Renewal dan Upgrade Asuransi Aswata/Matriks 6/6.3. Tracking Pengajuan</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>8915581f-cae7-4404-9d65-70b3001e12db</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS_Renewal dan Upgrade Asuransi Aswata/Matriks 7/7.1. Login - konsumen</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>73d99d93-9841-45b9-a729-1a9069621303</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS_Renewal dan Upgrade Asuransi Aswata/Matriks 7/7.3. Tracking Pengajuan</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>17947563-71a4-4feb-b944-401757372607</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS_Renewal dan Upgrade Asuransi Aswata/Matriks 8/8.1. Login - konsumen</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18f8f6fa-153d-412e-a420-dc8da24691a1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e84dd0b-fa9b-46a0-aeed-c5d0292305b5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7063da0b-67cb-41a4-9381-12d536d591ec</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS_Renewal dan Upgrade Asuransi Aswata/Matriks 8/8.3. Tracking Pengajuan</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>9578f5aa-8389-439a-9581-2cea507ae243</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS_Renewal dan Upgrade Asuransi Aswata/Matriks 9/9.1. Login - konsumen</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57f9a3da-90b0-4459-bb15-48b4742a6a9d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e93f43c3-91ad-4d23-a345-2ceb1c94eb8d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2df1a5fb-d3d7-49a8-b0f1-b1fdc864e913</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS_Renewal dan Upgrade Asuransi Aswata/Matriks 9/9.3. Tracking Pengajuan</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>cc00c445-fb2d-491d-8635-060ab3fd7c4b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS_Renewal dan Upgrade Asuransi Aswata/Matriks 9.10/10.1. Login - konsumen</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>357c52ae-1548-4336-9a8b-37c1a9de6902</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0cd87320-4c07-4721-9425-67f4b12120a4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>03449724-852b-4b75-b851-fb83ca6b80c3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS_Renewal dan Upgrade Asuransi Aswata/Matriks 9.10/10.3. Tracking Pengajuan</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>24103522-cd7a-484a-a0f0-7d579bc79b4a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS_Renewal dan Upgrade Asuransi Aswata/Matriks 9.11/11.1. Login - konsumen</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e35ab882-7c06-4628-a56c-ada36a292397</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99241ccc-667b-4d8b-b8a5-d4a00d558b01</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c42c4eac-aa56-4b20-949b-b940960024c4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS_Renewal dan Upgrade Asuransi Aswata/Matriks 9.11/11.3. Tracking Pengajuan</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>ccb42589-1a7b-47c4-b320-a7c304868d53</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS_Renewal dan Upgrade Asuransi Aswata/Matriks 9.12/12.1. Login - konsumen</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>93703920-d6bb-4b56-a871-9e7bd9421b76</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>254f2422-6b35-4a1e-81c2-4820f5940599</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c7d264ea-82ce-4782-b20e-f74f8719fd59</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS_Renewal dan Upgrade Asuransi Aswata/Matriks 9.12/12.3. Tracking Pengajuan</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>b65763fd-ce65-4f93-9a04-06e5079a4d99</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS_Renewal dan Upgrade Asuransi Aswata/Matriks 9.13/13.1. Login - konsumen</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb587577-f5df-4da2-8abf-851e5aa3f457</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fcc97095-f32c-465c-a371-b0b001791038</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7b00d61b-6453-41e6-93ee-6ffebfdc231a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS_Renewal dan Upgrade Asuransi Aswata/Matriks 9.13/13.3. Tracking Pengajuan</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>cae24019-d5e5-4ade-b62d-fd4443d6ac8e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS_Renewal dan Upgrade Asuransi Aswata/Matriks 9.14/14.1. Login - konsumen</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>a4a31142-7b81-46f8-bd2b-3984f006bdaa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS_Renewal dan Upgrade Asuransi Aswata/Matriks 9.14/14.3. Tracking Pengajuan</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>48c6d935-5486-4220-b1ee-99be70ef595c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS_Renewal dan Upgrade Asuransi Aswata/Matriks 9.15/15.1. Login - konsumen</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df999ffd-3b43-411f-845e-498af347f372</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf874406-e7eb-4bc7-9934-9ecea754e1d1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>70618723-9966-4291-9c59-ca34db16df99</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS_Renewal dan Upgrade Asuransi Aswata/Matriks 9.15/15.3. Tracking Pengajuan</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
