<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Report_Pengambilan_BPKB_KantorPusat_Dropdownval</name>
   <tag></tag>
   <elementGuidId>b65291d6-35fa-46c7-89de-7a0cb0d8c15c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='areaid']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;areaid&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>areaid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    -Pilih Lokasi Pengambilan-
                    BalikpapanBanda AcehBandungBanjarmasinBanyuwangiBatamBEKASIBengkuluBOGORBukit TinggiCilacapCirebonDAAN MOGOTDenpasarDepokDuriGorontaloGresikJambiJemberKantor PusatKarawangKediriKelapa GadingKendariKudusKupangLampungLubuk LinggauMadiunMagelangMakassarMalangMall Artha GadingMALL BASSURAManadoMataramMedanMuara BungoPadangPalangkarayaPalembangPaluPangkal PinangPare ParePekanbaruPematang SiantarPontianakProbolinggoPurwokertoSamarindaSampitSeason City MallSemarangSoloSukabumiSurabaya KlampisSurabaya VeteranTangerangTanjung PinangTasikmalayaTegalWTC Mangga DuaYogyakarta												
                </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/form[1]/table[1]/tbody[1]/tr[2]/td[2]/table[1]/tbody[1]/tr[3]/td[3]/select[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='areaid']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lokasi Pengambilan BPKB'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cabang Order'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
   </webElementXpaths>
</WebElementEntity>
