<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>1. Apply Online - Pengajuan Simulasi Budget</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>c3f42bd5-fce2-4870-80b9-64d1a7050e34</testSuiteGuid>
   <testCaseLink>
      <guid>99a1f676-9468-4539-b11c-781bd948c376</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS_Renewal dan Upgrade Asuransi Aswata/Matriks 8/8.1. Login - konsumen</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18f8f6fa-153d-412e-a420-dc8da24691a1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e84dd0b-fa9b-46a0-aeed-c5d0292305b5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c3e40f1e-a871-4f04-8971-46890c6194df</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/APN_ApplyOnlie/Simulasi Budget/1.1 Apply Online</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c21bde4-d240-422e-978f-b6d3daf07b2c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a70ac7e-07b3-4ad7-98cb-e3299b374143</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e9d173a-bfdb-4dbb-bac8-d36b8d6a41c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f9ec7d1-a351-4f9e-b9c6-de98cecd58f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e430e05d-4e53-4fd0-87ff-bb3365ab696f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5849c064-4bc2-4a9a-ba53-80235b4985ad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>601f213b-0630-4960-8219-e97f0c6d3299</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>521292ca-761b-45f7-8f97-94f8dffba9f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e58cba33-1c64-4429-9e02-b6f21743d59c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71ff735c-99c3-4fcd-9a5f-d04d39918b4c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a369450c-547c-455d-9131-c87a61b98c11</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad4d1e32-651b-432c-8551-a39854c5d662</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1afd5483-9d2c-49ac-ae08-fa6f0189518e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fbdc3b7e-281b-451f-9895-f37e5d06af43</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8d2fa2e-35c2-4da1-9c48-cf3c92b7f190</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fbbf7682-0faa-4aec-9a0f-5ef4e0fa210b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/APN_ApplyOnlie/Simulasi Budget/1.2 Data Kendaraan</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
